-- Groupware board: posts, comments, RLS, view-count RPC, attachment storage bucket.

BEGIN;

-- ---------------------------------------------------------------------------
-- board_posts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.board_posts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL DEFAULT 'general',
  title text NOT NULL,
  body_html text NOT NULL DEFAULT '',
  author_id uuid NOT NULL REFERENCES public.app_users (id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  view_count integer NOT NULL DEFAULT 0,
  comment_count integer NOT NULL DEFAULT 0,
  is_notice boolean NOT NULL DEFAULT false,
  has_attachments boolean NOT NULL DEFAULT false,
  has_images boolean NOT NULL DEFAULT false,
  CONSTRAINT board_posts_view_count_nonnegative CHECK (view_count >= 0),
  CONSTRAINT board_posts_comment_count_nonnegative CHECK (comment_count >= 0)
);

COMMENT ON TABLE public.board_posts IS 'Internal ERP bulletin board posts (HTML body).';
COMMENT ON COLUMN public.board_posts.has_attachments IS 'True when post has files in board_attachments storage.';
COMMENT ON COLUMN public.board_posts.has_images IS 'True when body or attachments include images; may be set client-side.';

CREATE INDEX IF NOT EXISTS idx_board_posts_created_at_desc
  ON public.board_posts (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_board_posts_view_count_desc
  ON public.board_posts (view_count DESC);

CREATE INDEX IF NOT EXISTS idx_board_posts_title
  ON public.board_posts (title);

CREATE OR REPLACE FUNCTION public.touch_board_posts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_board_posts_updated_at ON public.board_posts;
CREATE TRIGGER trg_touch_board_posts_updated_at
BEFORE UPDATE OF category, title, body_html, author_id, is_notice, has_attachments, has_images
ON public.board_posts
FOR EACH ROW
EXECUTE FUNCTION public.touch_board_posts_updated_at();

-- Only system admins may set or change is_notice (invoker context = end user).
CREATE OR REPLACE FUNCTION public.board_posts_enforce_notice_policy()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.is_notice IS TRUE AND NOT public.is_system_admin_user(auth.uid()) THEN
    RAISE EXCEPTION '공지 게시물은 관리자만 지정할 수 있습니다.';
  END IF;
  IF TG_OP = 'UPDATE'
     AND (OLD.is_notice IS DISTINCT FROM NEW.is_notice)
     AND NOT public.is_system_admin_user(auth.uid()) THEN
    RAISE EXCEPTION '공지 여부는 관리자만 변경할 수 있습니다.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_board_posts_enforce_notice_policy ON public.board_posts;
CREATE TRIGGER trg_board_posts_enforce_notice_policy
BEFORE INSERT OR UPDATE ON public.board_posts
FOR EACH ROW
EXECUTE FUNCTION public.board_posts_enforce_notice_policy();

-- ---------------------------------------------------------------------------
-- board_comments (+ comment_count on parent)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.board_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id uuid NOT NULL REFERENCES public.board_posts (id) ON DELETE CASCADE,
  author_id uuid NOT NULL REFERENCES public.app_users (id) ON DELETE RESTRICT,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.board_comments IS 'Bulletin board comments; comment_count on board_posts maintained by trigger.';

CREATE INDEX IF NOT EXISTS idx_board_comments_post_id_created_at
  ON public.board_comments (post_id, created_at ASC);

CREATE OR REPLACE FUNCTION public.board_comments_sync_post_comment_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.board_posts
    SET comment_count = comment_count + 1
    WHERE id = NEW.post_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.board_posts
    SET comment_count = GREATEST(0, comment_count - 1)
    WHERE id = OLD.post_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

REVOKE ALL ON FUNCTION public.board_comments_sync_post_comment_count() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_board_comments_sync_post_comment_count ON public.board_comments;
CREATE TRIGGER trg_board_comments_sync_post_comment_count
AFTER INSERT OR DELETE ON public.board_comments
FOR EACH ROW
EXECUTE FUNCTION public.board_comments_sync_post_comment_count();

-- ---------------------------------------------------------------------------
-- RPC: increment view_count (single round-trip; bypasses RLS via definer)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.increment_board_post_views(p_post_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer;
BEGIN
  UPDATE public.board_posts
  SET view_count = view_count + 1
  WHERE id = p_post_id
  RETURNING view_count INTO v_count;

  IF v_count IS NULL THEN
    RAISE EXCEPTION 'board post not found: %', p_post_id;
  END IF;

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.increment_board_post_views(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.increment_board_post_views(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_board_post_views(uuid) TO service_role;

-- ---------------------------------------------------------------------------
-- RLS: board_posts
-- ---------------------------------------------------------------------------
ALTER TABLE public.board_posts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS board_posts_select_authenticated ON public.board_posts;
CREATE POLICY board_posts_select_authenticated
ON public.board_posts
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS board_posts_insert_authenticated ON public.board_posts;
CREATE POLICY board_posts_insert_authenticated
ON public.board_posts
FOR INSERT
TO authenticated
WITH CHECK (author_id = auth.uid());

DROP POLICY IF EXISTS board_posts_update_authenticated ON public.board_posts;
CREATE POLICY board_posts_update_authenticated
ON public.board_posts
FOR UPDATE
TO authenticated
USING (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
)
WITH CHECK (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
);

DROP POLICY IF EXISTS board_posts_delete_authenticated ON public.board_posts;
CREATE POLICY board_posts_delete_authenticated
ON public.board_posts
FOR DELETE
TO authenticated
USING (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
);

-- ---------------------------------------------------------------------------
-- RLS: board_comments
-- ---------------------------------------------------------------------------
ALTER TABLE public.board_comments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS board_comments_select_authenticated ON public.board_comments;
CREATE POLICY board_comments_select_authenticated
ON public.board_comments
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS board_comments_insert_authenticated ON public.board_comments;
CREATE POLICY board_comments_insert_authenticated
ON public.board_comments
FOR INSERT
TO authenticated
WITH CHECK (author_id = auth.uid());

DROP POLICY IF EXISTS board_comments_update_authenticated ON public.board_comments;
CREATE POLICY board_comments_update_authenticated
ON public.board_comments
FOR UPDATE
TO authenticated
USING (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
)
WITH CHECK (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
);

DROP POLICY IF EXISTS board_comments_delete_authenticated ON public.board_comments;
CREATE POLICY board_comments_delete_authenticated
ON public.board_comments
FOR DELETE
TO authenticated
USING (
  author_id = auth.uid()
  OR public.is_system_admin_user(auth.uid())
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_posts TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.board_comments TO authenticated;

-- ---------------------------------------------------------------------------
-- Storage: board_attachments (same path pattern as approval_attachments)
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('board_attachments', 'board_attachments', true)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public;

DROP POLICY IF EXISTS board_attachments_select_public ON storage.objects;
CREATE POLICY board_attachments_select_public
ON storage.objects
FOR SELECT
TO public
USING (bucket_id = 'board_attachments');

DROP POLICY IF EXISTS board_attachments_insert_authenticated ON storage.objects;
CREATE POLICY board_attachments_insert_authenticated
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'board_attachments'
  AND (
    name LIKE auth.uid()::text || '/%'
    OR public.is_system_admin_user(auth.uid())
  )
);

DROP POLICY IF EXISTS board_attachments_update_authenticated ON storage.objects;
CREATE POLICY board_attachments_update_authenticated
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'board_attachments'
  AND (
    name LIKE auth.uid()::text || '/%'
    OR public.is_system_admin_user(auth.uid())
  )
)
WITH CHECK (
  bucket_id = 'board_attachments'
  AND (
    name LIKE auth.uid()::text || '/%'
    OR public.is_system_admin_user(auth.uid())
  )
);

DROP POLICY IF EXISTS board_attachments_delete_authenticated ON storage.objects;
CREATE POLICY board_attachments_delete_authenticated
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'board_attachments'
  AND (
    name LIKE auth.uid()::text || '/%'
    OR public.is_system_admin_user(auth.uid())
  )
);

COMMIT;
