BEGIN;

CREATE TABLE IF NOT EXISTS public.active_user_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL UNIQUE,
  user_id uuid REFERENCES public.app_users(id) ON DELETE CASCADE,
  email text,
  user_name text,
  ip text,
  user_agent text,
  current_path text,
  is_online boolean NOT NULL DEFAULT true,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_active_user_sessions_last_seen_at
  ON public.active_user_sessions (last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_active_user_sessions_user_id
  ON public.active_user_sessions (user_id);

ALTER TABLE public.active_user_sessions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS active_user_sessions_select_policy ON public.active_user_sessions;
CREATE POLICY active_user_sessions_select_policy
ON public.active_user_sessions
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
      FROM public.app_users u
     WHERE u.id = auth.uid()
       AND (
         lower(COALESCE(u.role_name, '')) = 'admin'
         OR COALESCE(u.can_manage_permissions, false) = true
       )
  )
);

ALTER TABLE public.warehouses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS warehouses_select_policy ON public.warehouses;
CREATE POLICY warehouses_select_policy
ON public.warehouses
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS warehouses_write_policy ON public.warehouses;
CREATE POLICY warehouses_write_policy
ON public.warehouses
FOR ALL
TO authenticated
USING (
  EXISTS (
    SELECT 1
      FROM public.app_users u
     WHERE u.id = auth.uid()
       AND (
         lower(COALESCE(u.role_name, '')) = 'admin'
         OR COALESCE(u.can_manage_permissions, false) = true
       )
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
      FROM public.app_users u
     WHERE u.id = auth.uid()
       AND (
         lower(COALESCE(u.role_name, '')) = 'admin'
         OR COALESCE(u.can_manage_permissions, false) = true
       )
  )
);

COMMIT;
