BEGIN;

CREATE TABLE IF NOT EXISTS public.approval_doc_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_doc_id bigint NOT NULL REFERENCES public.approval_docs(id) ON DELETE CASCADE,
  attachment_kind text NOT NULL CHECK (attachment_kind IN ('file', 'approval_doc')),
  file_name text NULL,
  storage_path text NULL,
  file_url text NULL,
  mime_type text NULL,
  file_size bigint NULL,
  related_approval_doc_id bigint NULL REFERENCES public.approval_docs(id) ON DELETE SET NULL,
  created_by uuid NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT approval_doc_attachments_kind_payload_check CHECK (
    (attachment_kind = 'file' AND file_url IS NOT NULL)
    OR (attachment_kind = 'approval_doc' AND related_approval_doc_id IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_approval_doc_attachments_doc_id
  ON public.approval_doc_attachments (approval_doc_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_approval_doc_attachments_related_id
  ON public.approval_doc_attachments (related_approval_doc_id);

CREATE OR REPLACE FUNCTION public.validate_approval_doc_attachment_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_related_writer uuid;
  v_related_status text;
BEGIN
  IF NEW.created_by IS NULL OR NEW.created_by <> auth.uid() THEN
    RAISE EXCEPTION '첨부 등록자는 현재 로그인 사용자와 같아야 합니다.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.approval_docs d
    WHERE d.id = NEW.approval_doc_id
      AND (
        public.is_system_admin_user(auth.uid())
        OR d.writer_id = auth.uid()
      )
  ) THEN
    RAISE EXCEPTION '현재 문서에 첨부를 등록할 권한이 없습니다.';
  END IF;

  IF NEW.attachment_kind = 'approval_doc' THEN
    SELECT d.writer_id, d.status
      INTO v_related_writer, v_related_status
      FROM public.approval_docs d
     WHERE d.id = NEW.related_approval_doc_id;

    IF v_related_writer IS NULL THEN
      RAISE EXCEPTION '첨부할 결재문서를 찾을 수 없습니다.';
    END IF;

    IF v_related_writer <> NEW.created_by THEN
      RAISE EXCEPTION '본인이 기안한 문서만 첨부할 수 있습니다.';
    END IF;

    IF COALESCE(v_related_status, '') <> 'approved' THEN
      RAISE EXCEPTION '최종 결재 완료(approved) 문서만 첨부할 수 있습니다.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_approval_doc_attachment_insert ON public.approval_doc_attachments;
CREATE TRIGGER trg_validate_approval_doc_attachment_insert
BEFORE INSERT ON public.approval_doc_attachments
FOR EACH ROW
EXECUTE FUNCTION public.validate_approval_doc_attachment_insert();

ALTER TABLE public.approval_doc_attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS approval_doc_attachments_select_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_select_policy
ON public.approval_doc_attachments
FOR SELECT
TO authenticated
USING (
  public.can_read_approval_doc(approval_doc_id, auth.uid())
);

DROP POLICY IF EXISTS approval_doc_attachments_insert_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_insert_policy
ON public.approval_doc_attachments
FOR INSERT
TO authenticated
WITH CHECK (
  created_by = auth.uid()
);

DROP POLICY IF EXISTS approval_doc_attachments_delete_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_delete_policy
ON public.approval_doc_attachments
FOR DELETE
TO authenticated
USING (
  public.is_system_admin_user(auth.uid())
  OR (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1
      FROM public.approval_docs d
      WHERE d.id = approval_doc_attachments.approval_doc_id
        AND d.writer_id = auth.uid()
    )
  )
);

COMMIT;
