-- Training ERP expansion:
-- - warehouse platform
-- - approval participants / visibility hardening
-- - login audit logs
-- - CoA file metadata
-- - employee number generation
-- - outbound RPC warehouse validation

BEGIN;

CREATE TABLE IF NOT EXISTS public.warehouses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.warehouses) THEN
    INSERT INTO public.warehouses (code, name, is_active, sort_order)
    VALUES ('WH-01', '기본 창고', true, 1);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.touch_updated_at_warehouses()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_updated_at_warehouses ON public.warehouses;
CREATE TRIGGER trg_touch_updated_at_warehouses
BEFORE UPDATE ON public.warehouses
FOR EACH ROW
EXECUTE FUNCTION public.touch_updated_at_warehouses();

CREATE OR REPLACE FUNCTION public.guard_warehouse_limit()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count FROM public.warehouses;
  IF v_count >= 20 THEN
    RAISE EXCEPTION 'Maximum warehouses reached (20)';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_guard_warehouse_limit ON public.warehouses;
CREATE TRIGGER trg_guard_warehouse_limit
BEFORE INSERT ON public.warehouses
FOR EACH ROW
EXECUTE FUNCTION public.guard_warehouse_limit();

ALTER TABLE public.inventory
  ADD COLUMN IF NOT EXISTS warehouse_id bigint;
ALTER TABLE public.inventory_transactions
  ADD COLUMN IF NOT EXISTS warehouse_id bigint;
ALTER TABLE public.outbound_requests
  ADD COLUMN IF NOT EXISTS warehouse_id bigint;

DO $$
DECLARE
  v_default_wh bigint;
BEGIN
  SELECT id INTO v_default_wh FROM public.warehouses ORDER BY sort_order, id LIMIT 1;

  UPDATE public.inventory
     SET warehouse_id = v_default_wh
   WHERE warehouse_id IS NULL;

  UPDATE public.inventory_transactions
     SET warehouse_id = COALESCE(
       warehouse_id,
       (SELECT inv.warehouse_id FROM public.inventory inv WHERE inv.id = inventory_transactions.inventory_id LIMIT 1),
       v_default_wh
     )
   WHERE warehouse_id IS NULL;

  UPDATE public.outbound_requests
     SET warehouse_id = v_default_wh
   WHERE warehouse_id IS NULL;
END $$;

ALTER TABLE public.inventory ALTER COLUMN warehouse_id SET NOT NULL;
ALTER TABLE public.outbound_requests ALTER COLUMN warehouse_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_warehouse_id_fkey') THEN
    ALTER TABLE public.inventory
      ADD CONSTRAINT inventory_warehouse_id_fkey
      FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_transactions_warehouse_id_fkey') THEN
    ALTER TABLE public.inventory_transactions
      ADD CONSTRAINT inventory_transactions_warehouse_id_fkey
      FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'outbound_requests_warehouse_id_fkey') THEN
    ALTER TABLE public.outbound_requests
      ADD CONSTRAINT outbound_requests_warehouse_id_fkey
      FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.login_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  email text,
  login_at timestamptz NOT NULL DEFAULT now(),
  ip text,
  user_agent text,
  success boolean NOT NULL DEFAULT false,
  session_id text
);

CREATE INDEX IF NOT EXISTS idx_login_audit_logs_login_at ON public.login_audit_logs (login_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_logs_user_id ON public.login_audit_logs (user_id);

ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS employee_no text;
CREATE UNIQUE INDEX IF NOT EXISTS uq_app_users_employee_no
  ON public.app_users (employee_no)
  WHERE employee_no IS NOT NULL;

CREATE OR REPLACE FUNCTION public.next_employee_no(p_now timestamptz DEFAULT now())
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_yy text := to_char(p_now, 'YY');
  v_prefix text := v_yy || '-';
  v_last text;
  v_seq integer := 1;
BEGIN
  SELECT employee_no
    INTO v_last
    FROM public.app_users
   WHERE employee_no LIKE v_prefix || '%'
   ORDER BY employee_no DESC
   LIMIT 1;
  IF v_last IS NOT NULL THEN
    v_seq := COALESCE(NULLIF(split_part(v_last, '-', 2), '')::integer, 0) + 1;
  END IF;
  RETURN v_prefix || lpad(v_seq::text, 4, '0');
END;
$$;

CREATE TABLE IF NOT EXISTS public.approval_participants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  approval_doc_id bigint NOT NULL REFERENCES public.approval_docs(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK (role IN ('reviewer', 'pre_cooperator', 'final_approver', 'post_cooperator', 'reference')),
  line_no integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (approval_doc_id, user_id, role)
);

CREATE INDEX IF NOT EXISTS idx_approval_participants_doc_id ON public.approval_participants (approval_doc_id);
CREATE INDEX IF NOT EXISTS idx_approval_participants_user_id ON public.approval_participants (user_id);

INSERT INTO public.approval_participants (approval_doc_id, user_id, role, line_no)
SELECT
  l.approval_doc_id,
  l.approver_id,
  CASE
    WHEN l.approver_role = 'review' THEN 'reviewer'
    WHEN l.approver_role = 'approve' THEN 'final_approver'
    ELSE 'reference'
  END AS role,
  l.line_no
FROM public.approval_lines l
ON CONFLICT (approval_doc_id, user_id, role) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.coa_files (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  warehouse_id bigint REFERENCES public.warehouses(id) ON DELETE SET NULL,
  version_no integer NOT NULL DEFAULT 1,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  file_size bigint,
  is_active boolean NOT NULL DEFAULT true,
  uploaded_by uuid REFERENCES public.app_users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (item_id, warehouse_id, version_no),
  UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_coa_files_item_id ON public.coa_files (item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_coa_files_active ON public.coa_files (is_active);

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_lines_approval_doc_id_fkey') THEN
    ALTER TABLE public.approval_lines DROP CONSTRAINT approval_lines_approval_doc_id_fkey;
  END IF;
  ALTER TABLE public.approval_lines
    ADD CONSTRAINT approval_lines_approval_doc_id_fkey
    FOREIGN KEY (approval_doc_id) REFERENCES public.approval_docs(id) ON DELETE CASCADE;

  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'approval_histories_approval_doc_id_fkey') THEN
    ALTER TABLE public.approval_histories DROP CONSTRAINT approval_histories_approval_doc_id_fkey;
  END IF;
  ALTER TABLE public.approval_histories
    ADD CONSTRAINT approval_histories_approval_doc_id_fkey
    FOREIGN KEY (approval_doc_id) REFERENCES public.approval_docs(id) ON DELETE CASCADE;

  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'outbound_requests_approval_doc_id_fkey') THEN
    ALTER TABLE public.outbound_requests DROP CONSTRAINT outbound_requests_approval_doc_id_fkey;
  END IF;
  ALTER TABLE public.outbound_requests
    ADD CONSTRAINT outbound_requests_approval_doc_id_fkey
    FOREIGN KEY (approval_doc_id) REFERENCES public.approval_docs(id) ON DELETE CASCADE;

  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'outbound_request_items_outbound_request_id_fkey') THEN
    ALTER TABLE public.outbound_request_items DROP CONSTRAINT outbound_request_items_outbound_request_id_fkey;
  END IF;
  ALTER TABLE public.outbound_request_items
    ADD CONSTRAINT outbound_request_items_outbound_request_id_fkey
    FOREIGN KEY (outbound_request_id) REFERENCES public.outbound_requests(id) ON DELETE CASCADE;
END $$;

ALTER TABLE public.approval_docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outbound_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coa_files ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS approval_docs_select_policy ON public.approval_docs;
CREATE POLICY approval_docs_select_policy
ON public.approval_docs
FOR SELECT
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.app_users u WHERE u.id = auth.uid() AND lower(COALESCE(u.role_name, '')) = 'admin')
  OR writer_id = auth.uid()
  OR EXISTS (
    SELECT 1
      FROM public.approval_participants p
     WHERE p.approval_doc_id = approval_docs.id
       AND p.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS approval_participants_select_policy ON public.approval_participants;
CREATE POLICY approval_participants_select_policy
ON public.approval_participants
FOR SELECT
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.app_users u WHERE u.id = auth.uid() AND lower(COALESCE(u.role_name, '')) = 'admin')
  OR user_id = auth.uid()
  OR EXISTS (
    SELECT 1
      FROM public.approval_docs d
     WHERE d.id = approval_participants.approval_doc_id
       AND d.writer_id = auth.uid()
  )
);

DROP POLICY IF EXISTS outbound_requests_select_policy ON public.outbound_requests;
CREATE POLICY outbound_requests_select_policy
ON public.outbound_requests
FOR SELECT
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.app_users u WHERE u.id = auth.uid() AND lower(COALESCE(u.role_name, '')) = 'admin')
  OR requester_id = auth.uid()
  OR EXISTS (
    SELECT 1
      FROM public.approval_participants p
      JOIN public.approval_docs d ON d.id = p.approval_doc_id
     WHERE p.user_id = auth.uid()
       AND d.id = outbound_requests.approval_doc_id
  )
);

DROP POLICY IF EXISTS coa_files_select_policy ON public.coa_files;
CREATE POLICY coa_files_select_policy
ON public.coa_files
FOR SELECT
TO authenticated
USING (
  EXISTS (SELECT 1 FROM public.app_users u WHERE u.id = auth.uid() AND lower(COALESCE(u.role_name, '')) = 'admin')
  OR EXISTS (
    SELECT 1
      FROM public.outbound_request_items ori
      JOIN public.outbound_requests r ON r.id = ori.outbound_request_id
      LEFT JOIN public.approval_participants p ON p.approval_doc_id = r.approval_doc_id
      JOIN public.approval_docs d ON d.id = r.approval_doc_id
     WHERE ori.item_id = coa_files.item_id
       AND (
         r.requester_id = auth.uid()
         OR d.writer_id = auth.uid()
         OR p.user_id = auth.uid()
       )
  )
);

DROP POLICY IF EXISTS coa_files_insert_policy ON public.coa_files;
CREATE POLICY coa_files_insert_policy
ON public.coa_files
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
      FROM public.app_users u
     WHERE u.id = auth.uid()
       AND (
         lower(COALESCE(u.role_name, '')) = 'admin'
         OR COALESCE(u.can_manage_permissions, false) = true
       )
  )
);

DROP POLICY IF EXISTS login_audit_logs_select_policy ON public.login_audit_logs;
CREATE POLICY login_audit_logs_select_policy
ON public.login_audit_logs
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
      FROM public.app_users u
     WHERE u.id = auth.uid()
       AND (
         lower(COALESCE(u.role_name, '')) = 'admin'
         OR COALESCE(u.can_manage_permissions, false) = true
       )
  )
);

DROP POLICY IF EXISTS login_audit_logs_insert_policy ON public.login_audit_logs;
CREATE POLICY login_audit_logs_insert_policy
ON public.login_audit_logs
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.execute_outbound_request_fulfillment(
  p_outbound_request_id bigint,
  p_lines jsonb
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_req public.outbound_requests%ROWTYPE;
  v_line jsonb;
  v_inv public.inventory%ROWTYPE;
  v_qty numeric;
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  SELECT * INTO v_req
    FROM public.outbound_requests
   WHERE id = p_outbound_request_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'outbound_request not found: %', p_outbound_request_id;
  END IF;
  IF v_req.status IS DISTINCT FROM 'approved' THEN
    RAISE EXCEPTION 'outbound_request must be approved (current status: %)', v_req.status;
  END IF;
  IF p_lines IS NULL OR jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'p_lines must be a non-empty json array';
  END IF;
  IF v_req.warehouse_id IS NULL THEN
    RAISE EXCEPTION 'warehouse must be set on outbound request';
  END IF;

  FOR v_line IN SELECT * FROM jsonb_array_elements(p_lines)
  LOOP
    v_qty := (v_line ->> 'qty')::numeric;
    IF v_qty IS NULL OR v_qty <= 0 THEN
      RAISE EXCEPTION 'invalid qty in line: %', v_line;
    END IF;

    SELECT * INTO v_inv
      FROM public.inventory
     WHERE id = (v_line ->> 'inventory_id')::bigint
     FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'inventory row not found: %', (v_line ->> 'inventory_id');
    END IF;
    IF v_inv.item_id IS DISTINCT FROM (v_line ->> 'item_id')::bigint THEN
      RAISE EXCEPTION 'item_id does not match inventory row';
    END IF;
    IF v_inv.warehouse_id IS DISTINCT FROM v_req.warehouse_id THEN
      RAISE EXCEPTION 'warehouse mismatch for inventory_id % (inv %, req %)', v_inv.id, v_inv.warehouse_id, v_req.warehouse_id;
    END IF;
    IF v_inv.current_qty < v_qty THEN
      RAISE EXCEPTION 'insufficient stock for inventory_id % (have %, need %)', v_inv.id, v_inv.current_qty, v_qty;
    END IF;

    UPDATE public.inventory
       SET current_qty = current_qty - v_qty,
           available_qty = available_qty - v_qty,
           updated_at = now()
     WHERE id = v_inv.id;

    INSERT INTO public.inventory_transactions (
      item_id, trans_type, qty, lot_no, exp_date, serial_no,
      remarks, trans_date, actor_id, created_by, ref_table, ref_id,
      inventory_id, warehouse_id
    ) VALUES (
      v_inv.item_id, 'OUT', v_qty, v_inv.lot_no, v_inv.exp_date, v_inv.serial_no,
      format('출고요청(%s) 기반', v_req.req_no), now(), v_actor, v_actor, 'outbound_requests', p_outbound_request_id,
      v_inv.id, v_inv.warehouse_id
    );
  END LOOP;

  UPDATE public.outbound_requests
     SET status = 'completed', updated_at = now()
   WHERE id = p_outbound_request_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_outbound_cancellation(p_doc_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor uuid := auth.uid();
  v_req public.outbound_requests%ROWTYPE;
  r_tx public.inventory_transactions%ROWTYPE;
  v_req_no text;
  v_pattern text;
BEGIN
  IF v_actor IS NULL THEN
    RAISE EXCEPTION 'not authenticated';
  END IF;

  SELECT * INTO v_req
    FROM public.outbound_requests
   WHERE approval_doc_id = p_doc_id
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'outbound_request not found for approval_doc_id %', p_doc_id;
  END IF;

  v_req_no := coalesce(v_req.req_no::text, '');
  v_pattern := '%출고요청(' || v_req_no || ')%';

  FOR r_tx IN
    SELECT *
      FROM public.inventory_transactions
     WHERE trans_type = 'OUT'
       AND (
         (ref_table = 'outbound_requests' AND ref_id = v_req.id)
         OR (ref_table IS NULL AND ref_id IS NULL AND remarks LIKE v_pattern)
       )
     ORDER BY id
  LOOP
    IF r_tx.inventory_id IS NOT NULL THEN
      UPDATE public.inventory
         SET current_qty = current_qty + r_tx.qty,
             available_qty = available_qty + r_tx.qty,
             updated_at = now()
       WHERE id = r_tx.inventory_id
         AND warehouse_id = v_req.warehouse_id;
    ELSE
      UPDATE public.inventory inv
         SET current_qty = inv.current_qty + r_tx.qty,
             available_qty = inv.available_qty + r_tx.qty,
             updated_at = now()
        FROM (
          SELECT id
            FROM public.inventory
           WHERE item_id = r_tx.item_id
             AND warehouse_id = v_req.warehouse_id
             AND lot_no IS NOT DISTINCT FROM r_tx.lot_no
             AND exp_date IS NOT DISTINCT FROM r_tx.exp_date
             AND serial_no IS NOT DISTINCT FROM r_tx.serial_no
           ORDER BY id
           LIMIT 1
        ) pick
       WHERE inv.id = pick.id;
    END IF;

    DELETE FROM public.inventory_transactions WHERE id = r_tx.id;
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.execute_outbound_request_fulfillment(bigint, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.execute_outbound_request_fulfillment(bigint, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.execute_outbound_request_fulfillment(bigint, jsonb) TO service_role;

REVOKE ALL ON FUNCTION public.finalize_outbound_cancellation(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finalize_outbound_cancellation(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_outbound_cancellation(bigint) TO service_role;

COMMIT;
