BEGIN;

CREATE TABLE IF NOT EXISTS public.inbound_upload_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_type text NOT NULL CHECK (source_type IN ('single', 'template')),
  file_name text NULL,
  total_rows integer NOT NULL DEFAULT 0,
  success_rows integer NOT NULL DEFAULT 0,
  failed_rows integer NOT NULL DEFAULT 0,
  requested_by uuid NULL REFERENCES public.app_users(id) ON DELETE SET NULL,
  summary jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inbound_upload_log_rows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  log_id bigint NOT NULL REFERENCES public.inbound_upload_logs(id) ON DELETE CASCADE,
  row_no integer NOT NULL,
  status text NOT NULL CHECK (status IN ('success', 'failed')),
  message text NULL,
  item_code text NULL,
  warehouse_code text NULL,
  customer_code text NULL,
  qty numeric NULL,
  lot_no text NULL,
  exp_date date NULL,
  serial_no text NULL,
  raw_row jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_inbound_upload_logs_requested_by
  ON public.inbound_upload_logs (requested_by, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_inbound_upload_log_rows_log_id
  ON public.inbound_upload_log_rows (log_id, row_no);

ALTER TABLE public.inbound_upload_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_upload_log_rows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS inbound_upload_logs_select_policy ON public.inbound_upload_logs;
CREATE POLICY inbound_upload_logs_select_policy
ON public.inbound_upload_logs
FOR SELECT
TO authenticated
USING (
  requested_by = auth.uid()
  OR public.is_system_admin_user(auth.uid())
);

DROP POLICY IF EXISTS inbound_upload_logs_insert_policy ON public.inbound_upload_logs;
CREATE POLICY inbound_upload_logs_insert_policy
ON public.inbound_upload_logs
FOR INSERT
TO authenticated
WITH CHECK (requested_by = auth.uid() OR public.is_system_admin_user(auth.uid()));

DROP POLICY IF EXISTS inbound_upload_logs_update_policy ON public.inbound_upload_logs;
CREATE POLICY inbound_upload_logs_update_policy
ON public.inbound_upload_logs
FOR UPDATE
TO authenticated
USING (requested_by = auth.uid() OR public.is_system_admin_user(auth.uid()))
WITH CHECK (requested_by = auth.uid() OR public.is_system_admin_user(auth.uid()));

DROP POLICY IF EXISTS inbound_upload_log_rows_select_policy ON public.inbound_upload_log_rows;
CREATE POLICY inbound_upload_log_rows_select_policy
ON public.inbound_upload_log_rows
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.inbound_upload_logs h
    WHERE h.id = inbound_upload_log_rows.log_id
      AND (h.requested_by = auth.uid() OR public.is_system_admin_user(auth.uid()))
  )
);

DROP POLICY IF EXISTS inbound_upload_log_rows_insert_policy ON public.inbound_upload_log_rows;
CREATE POLICY inbound_upload_log_rows_insert_policy
ON public.inbound_upload_log_rows
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.inbound_upload_logs h
    WHERE h.id = inbound_upload_log_rows.log_id
      AND (h.requested_by = auth.uid() OR public.is_system_admin_user(auth.uid()))
  )
);

COMMIT;
