BEGIN;

ALTER TABLE public.approval_doc_attachments
  ALTER COLUMN approval_doc_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS draft_session_key text NULL,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'temp',
  ADD COLUMN IF NOT EXISTS last_autosave_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS expires_at timestamptz NULL,
  ADD COLUMN IF NOT EXISTS cleanup_attempts integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_cleanup_error text NULL,
  ADD COLUMN IF NOT EXISTS cleaned_at timestamptz NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'approval_doc_attachments_status_check'
      AND conrelid = 'public.approval_doc_attachments'::regclass
  ) THEN
    ALTER TABLE public.approval_doc_attachments
      ADD CONSTRAINT approval_doc_attachments_status_check
      CHECK (status IN ('temp', 'linked', 'deleted', 'cleanup_failed'));
  END IF;
END $$;

ALTER TABLE public.approval_doc_attachments
  DROP CONSTRAINT IF EXISTS approval_doc_attachments_kind_payload_check;

ALTER TABLE public.approval_doc_attachments
  ADD CONSTRAINT approval_doc_attachments_kind_payload_check
  CHECK (
    (
      attachment_kind = 'file'
      AND file_url IS NOT NULL
    )
    OR (
      attachment_kind = 'approval_doc'
      AND related_approval_doc_id IS NOT NULL
    )
  );

ALTER TABLE public.approval_doc_attachments
  DROP CONSTRAINT IF EXISTS approval_doc_attachments_doc_or_session_check;

ALTER TABLE public.approval_doc_attachments
  ADD CONSTRAINT approval_doc_attachments_doc_or_session_check
  CHECK (approval_doc_id IS NOT NULL OR COALESCE(draft_session_key, '') <> '');

CREATE INDEX IF NOT EXISTS idx_approval_doc_attachments_session
  ON public.approval_doc_attachments (draft_session_key, created_by, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_approval_doc_attachments_expire_temp
  ON public.approval_doc_attachments (expires_at)
  WHERE status = 'temp';

CREATE TABLE IF NOT EXISTS public.attachment_cleanup_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz NULL,
  scanned_count integer NOT NULL DEFAULT 0,
  deleted_count integer NOT NULL DEFAULT 0,
  failed_count integer NOT NULL DEFAULT 0,
  note text NULL
);

CREATE TABLE IF NOT EXISTS public.attachment_cleanup_errors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id bigint NULL REFERENCES public.attachment_cleanup_runs(id) ON DELETE SET NULL,
  attachment_id bigint NOT NULL REFERENCES public.approval_doc_attachments(id) ON DELETE CASCADE,
  storage_path text NULL,
  error_message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.attachment_cleanup_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachment_cleanup_errors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS approval_doc_attachments_select_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_select_policy
ON public.approval_doc_attachments
FOR SELECT
TO authenticated
USING (
  (
    approval_doc_id IS NOT NULL
    AND public.can_read_approval_doc(approval_doc_id, auth.uid())
  )
  OR (
    approval_doc_id IS NULL
    AND created_by = auth.uid()
  )
);

DROP POLICY IF EXISTS approval_doc_attachments_insert_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_insert_policy
ON public.approval_doc_attachments
FOR INSERT
TO authenticated
WITH CHECK (created_by = auth.uid());

DROP POLICY IF EXISTS approval_doc_attachments_delete_policy ON public.approval_doc_attachments;
CREATE POLICY approval_doc_attachments_delete_policy
ON public.approval_doc_attachments
FOR DELETE
TO authenticated
USING (
  public.is_system_admin_user(auth.uid())
  OR (
    created_by = auth.uid()
    AND (
      approval_doc_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM public.approval_docs d
        WHERE d.id = approval_doc_attachments.approval_doc_id
          AND d.writer_id = auth.uid()
      )
    )
  )
);

DROP POLICY IF EXISTS attachment_cleanup_runs_select_admin ON public.attachment_cleanup_runs;
CREATE POLICY attachment_cleanup_runs_select_admin
ON public.attachment_cleanup_runs
FOR SELECT
TO authenticated
USING (public.is_system_admin_user(auth.uid()));

DROP POLICY IF EXISTS attachment_cleanup_errors_select_admin ON public.attachment_cleanup_errors;
CREATE POLICY attachment_cleanup_errors_select_admin
ON public.attachment_cleanup_errors
FOR SELECT
TO authenticated
USING (public.is_system_admin_user(auth.uid()));

CREATE OR REPLACE FUNCTION public.touch_temp_approval_attachments(
  p_draft_session_key text,
  p_actor_id uuid,
  p_ttl_hours integer DEFAULT 72
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count integer := 0;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_actor_id THEN
    RAISE EXCEPTION '권한이 없습니다.';
  END IF;
  IF COALESCE(trim(p_draft_session_key), '') = '' THEN
    RETURN 0;
  END IF;

  UPDATE public.approval_doc_attachments
     SET last_autosave_at = now(),
         expires_at = now() + make_interval(hours => GREATEST(p_ttl_hours, 1))
   WHERE draft_session_key = p_draft_session_key
     AND created_by = p_actor_id
     AND status = 'temp'
     AND approval_doc_id IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.touch_temp_approval_attachments(text, uuid, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.touch_temp_approval_attachments(text, uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.touch_temp_approval_attachments(text, uuid, integer) TO service_role;

CREATE OR REPLACE FUNCTION public.validate_approval_doc_attachment_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_related_writer uuid;
  v_related_status text;
BEGIN
  IF NEW.created_by IS NULL OR NEW.created_by <> auth.uid() THEN
    RAISE EXCEPTION '첨부 등록자는 현재 로그인 사용자와 같아야 합니다.';
  END IF;

  IF NEW.approval_doc_id IS NOT NULL THEN
    IF NOT EXISTS (
      SELECT 1
      FROM public.approval_docs d
      WHERE d.id = NEW.approval_doc_id
        AND (
          public.is_system_admin_user(auth.uid())
          OR d.writer_id = auth.uid()
        )
    ) THEN
      RAISE EXCEPTION '현재 문서에 첨부를 등록할 권한이 없습니다.';
    END IF;
    NEW.status := COALESCE(NULLIF(NEW.status, ''), 'linked');
    NEW.expires_at := NULL;
  ELSE
    IF COALESCE(trim(NEW.draft_session_key), '') = '' THEN
      RAISE EXCEPTION '임시 첨부에는 draft_session_key가 필요합니다.';
    END IF;
    NEW.status := COALESCE(NULLIF(NEW.status, ''), 'temp');
    IF NEW.last_autosave_at IS NULL THEN
      NEW.last_autosave_at := now();
    END IF;
    IF NEW.expires_at IS NULL THEN
      NEW.expires_at := now() + interval '72 hours';
    END IF;
  END IF;

  IF NEW.attachment_kind = 'approval_doc' THEN
    SELECT d.writer_id, d.status
      INTO v_related_writer, v_related_status
      FROM public.approval_docs d
     WHERE d.id = NEW.related_approval_doc_id;

    IF v_related_writer IS NULL THEN
      RAISE EXCEPTION '첨부할 결재문서를 찾을 수 없습니다.';
    END IF;
    IF v_related_writer <> NEW.created_by THEN
      RAISE EXCEPTION '본인이 기안한 문서만 첨부할 수 있습니다.';
    END IF;
    IF COALESCE(v_related_status, '') <> 'approved' THEN
      RAISE EXCEPTION '최종 결재 완료(approved) 문서만 첨부할 수 있습니다.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.link_temp_approval_attachments(
  p_draft_session_key text,
  p_approval_doc_id bigint,
  p_actor_id uuid
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_writer uuid;
  v_count integer := 0;
BEGIN
  IF auth.uid() IS NULL OR auth.uid() <> p_actor_id THEN
    RAISE EXCEPTION '권한이 없습니다.';
  END IF;
  IF COALESCE(trim(p_draft_session_key), '') = '' THEN
    RETURN 0;
  END IF;

  SELECT d.writer_id INTO v_writer
    FROM public.approval_docs d
   WHERE d.id = p_approval_doc_id;

  IF v_writer IS NULL THEN
    RAISE EXCEPTION '연결할 결재문서를 찾을 수 없습니다.';
  END IF;
  IF v_writer <> p_actor_id AND NOT public.is_system_admin_user(auth.uid()) THEN
    RAISE EXCEPTION '해당 문서에 첨부를 연결할 권한이 없습니다.';
  END IF;

  UPDATE public.approval_doc_attachments
     SET approval_doc_id = p_approval_doc_id,
         status = 'linked',
         expires_at = NULL
   WHERE draft_session_key = p_draft_session_key
     AND created_by = p_actor_id
     AND status = 'temp'
     AND approval_doc_id IS NULL;

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.link_temp_approval_attachments(text, bigint, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.link_temp_approval_attachments(text, bigint, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.link_temp_approval_attachments(text, bigint, uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.cleanup_expired_temp_approval_attachments(
  p_limit integer DEFAULT 200
)
RETURNS TABLE(run_id bigint, deleted_count integer, failed_count integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_run_id bigint;
  v_deleted integer := 0;
  v_failed integer := 0;
  v_limit integer := GREATEST(COALESCE(p_limit, 200), 1);
  r RECORD;
BEGIN
  IF auth.uid() IS NULL OR NOT public.is_system_admin_user(auth.uid()) THEN
    RAISE EXCEPTION '관리자만 실행할 수 있습니다.';
  END IF;

  INSERT INTO public.attachment_cleanup_runs(note) VALUES ('scheduled/manual cleanup')
  RETURNING id INTO v_run_id;

  FOR r IN
    SELECT a.id, a.storage_path
      FROM public.approval_doc_attachments a
     WHERE a.status = 'temp'
       AND a.approval_doc_id IS NULL
       AND a.expires_at IS NOT NULL
       AND a.expires_at < now()
     ORDER BY a.expires_at ASC
     LIMIT v_limit
  LOOP
    BEGIN
      IF COALESCE(r.storage_path, '') <> '' THEN
        DELETE FROM storage.objects
         WHERE bucket_id = 'approval_attachments'
           AND name = r.storage_path;
      END IF;

      UPDATE public.approval_doc_attachments
         SET status = 'deleted',
             cleaned_at = now(),
             last_cleanup_error = NULL
       WHERE id = r.id;
      v_deleted := v_deleted + 1;
    EXCEPTION WHEN OTHERS THEN
      v_failed := v_failed + 1;
      UPDATE public.approval_doc_attachments
         SET cleanup_attempts = cleanup_attempts + 1,
             last_cleanup_error = SQLERRM,
             status = CASE WHEN cleanup_attempts + 1 >= 5 THEN 'cleanup_failed' ELSE status END
       WHERE id = r.id;
      INSERT INTO public.attachment_cleanup_errors(run_id, attachment_id, storage_path, error_message)
      VALUES (v_run_id, r.id, r.storage_path, SQLERRM);
    END;
  END LOOP;

  UPDATE public.attachment_cleanup_runs
     SET finished_at = now(),
         scanned_count = v_deleted + v_failed,
         deleted_count = v_deleted,
         failed_count = v_failed
   WHERE id = v_run_id;

  RETURN QUERY SELECT v_run_id, v_deleted, v_failed;
END;
$$;

REVOKE ALL ON FUNCTION public.cleanup_expired_temp_approval_attachments(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_temp_approval_attachments(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cleanup_expired_temp_approval_attachments(integer) TO service_role;

COMMIT;
