BEGIN;

CREATE TABLE IF NOT EXISTS public.outbound_dispatch_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  outbound_request_id bigint NOT NULL,
  approval_doc_id bigint,
  action_type text NOT NULL CHECK (action_type IN ('assign', 'reassign', 'recall', 'execute_self', 'complete')),
  actor_id uuid NOT NULL,
  actor_name text,
  reason text,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  before_state jsonb NOT NULL,
  after_state jsonb NOT NULL,
  dedupe_key text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outbound_dispatch_audit_logs_request_id
  ON public.outbound_dispatch_audit_logs (outbound_request_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS idx_outbound_dispatch_audit_logs_approval_doc_id
  ON public.outbound_dispatch_audit_logs (approval_doc_id, occurred_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_outbound_dispatch_audit_logs_dedupe_key
  ON public.outbound_dispatch_audit_logs (dedupe_key)
  WHERE dedupe_key IS NOT NULL;

CREATE OR REPLACE FUNCTION public.prevent_outbound_dispatch_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'outbound_dispatch_audit_logs rows are immutable';
END;
$$;

DROP TRIGGER IF EXISTS trg_outbound_dispatch_audit_logs_no_update
ON public.outbound_dispatch_audit_logs;
CREATE TRIGGER trg_outbound_dispatch_audit_logs_no_update
BEFORE UPDATE ON public.outbound_dispatch_audit_logs
FOR EACH ROW
EXECUTE FUNCTION public.prevent_outbound_dispatch_audit_mutation();

DROP TRIGGER IF EXISTS trg_outbound_dispatch_audit_logs_no_delete
ON public.outbound_dispatch_audit_logs;
CREATE TRIGGER trg_outbound_dispatch_audit_logs_no_delete
BEFORE DELETE ON public.outbound_dispatch_audit_logs
FOR EACH ROW
EXECUTE FUNCTION public.prevent_outbound_dispatch_audit_mutation();

COMMIT;
